version: "3.7"
services:
  app:
    build:
      args:
        user: gabriel
        uid: 1000
      context: docker
      dockerfile: Dockerfile
    image: melhorpreco
    container_name: melhorpreco-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php_custom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - melhorpreco
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
  db:
    image: postgres:13.4
    container_name: melhorpreco-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DATABASE: ${DB_DATABASE}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
    - melhorpreco
  nginx:
    image: nginx:1.17-alpine
    container_name: melhorpreco-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - melhorpreco
networks:
  melhorpreco:
    driver: bridge
volumes:
  db_data:
    driver: local
