require('./costs/navbar')
require('./product/upload_image')
require('./pricing/inputs')
// require('./notifications/notifications')
require('./marketplaces/navbar')
require('./marketplaces/category_commission')
require('./users/registration_form')
