name: Pull Requests WorkFlow

on:
  pull_request:
    branches:
      - master

jobs:
  app-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13.4
        env:
          DB_DATABASE: barrigudinha_test
          DB_USERNAME: barrigudinha_user
          DB_PASSWORD: barrigudinha_password
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
    steps:
      - uses: actions/checkout@v1
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.testing', '.env');"
      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Install NPM Dependencies
        run: npm install
      - name: Generate key
        run: php artisan key:generate
      - name: Setup Project
        run: composer setup-dev
      - name: Execute tests using PHPUnit
        env:
          DB_PORT: ${{ job.services.postgres.ports[5432] }}
        run: ./vendor/bin/phpunit
